# Generated by Django 5.2.4 on 2025-08-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_productimage_image_alter_product_image_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_worthy_pick',
            field=models.BooleanField(default=False),
        ),
    ]
