# Generated by Django 5.2.4 on 2025-08-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0011_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="on_sale",
            field=models.BooleanField(default=False),
        ),
    ]
